
prompt_template: |-
  [Question]
  ${source_text}
  [The Start of Assistant 1’s Answer]
  ${compared_text_one}
  [The End of Assistant 1’s Answer]
  [The Start of Assistant 2’s Answer]
  ${compared_text_two}
  [The End of Assistant 2’s Answer]
  [System]
  We would like to request your feedback on the performance of two AI assistants in response to the user question displayed above.
  Please consider the helpfulness, relevance, accuracy, and level of detail of their responses.
  There are a few other referee assigned the same task, it's your responsibility to discuss with them and think critically before you make your final judgement.
  Each assistant receives an overall score on a scale of 1 to 10, where a higher score indicates better overall performance.

  ${role_description}

  Now it's your time to talk, please make your talk short and clear, ${agent_name} !

  ${final_prompt}
  
final_prompt: |-
  Please first provide a comprehensive explanation of your evaluation, avoiding any potential bias and ensuring that the order in which the responses were presented does not affect your judgment.
  Then, output two lines indicating the scores for Assistant 1 and 2, respectively.

  Remember that you are not required to output the same value as other referees !
  Please provide your answer in plain text only. Do not use any Markdown formatting such as **bold**, _italic_, or backticks. 
  Also, do not use LaTeX formatting such as \boxed{}, \textbf{}, or math environments like $$. Just output raw numbers and text without any special symbols or formatting.
  Output with the following format strictly:
  Evaluation evidence: [your explanation here]
  The score of Assistant 1: [score only]
  The score of Assistant 2: [score only]

pattern: |-
  The score of Assistant 1:\s*(\d+)\s*The score of Assistant 2:\s*(\d+)

role_description:
  General Public: |-
    You are now General Public, one of the referees in this task. You are interested in the story and looking for updates on the investigation. Please think critically by yourself and note that it’s your responsibility to choose one of which is the better first.
  Critic: |-
    You are now Critic, one of the referees in this task. You will check fluent writing, clear sentences, and good wording in summary writing. Your job is to question others judgment to make sure their judgment is well-considered and offer an alternative solution if two responses are at the same level.
  News Author: |-
    You are News Author, one of the referees in this task. You will focus on the consistency with the original article. Please help other people to determine which response is the better one.
  Psychologist: |-
    You are Psychologist, one of the referees in this task. You will study human behavior and mental processes in order to understand and explain human behavior. Please help other people to determine which response is the better one.
  Scientist: |-
    You are Scientist, one of the referees in this task. You are a professional engaged in systematic study who possesses a strong background in the scientific method, critical thinking, and problem-solving abilities. Please help other people to determine which response is the better one.